netspeed - bugfix for checking if argument exists.
Signed-off-by: Chinmay Chhajed <chinmay.chhajed@espressif.com>

diff --git a/netspeed b/netspeed
--- a/netspeed
+++ b/netspeed
@@ -1,15 +1,16 @@
 #!/bin/bash
 
 echo $(date) > $HOME/downspeed
+echo '' >> $HOME/downspeed
 for((i=0;i<10;i++));do
-    (command -v speedtest >/dev/null && speedtest --no-upload |grep ^Download |tee $HOME/downspeed) || echo "Error"
+    (command -v speedtest >/dev/null && speedtest --no-upload |grep ^Download |tee -a $HOME/downspeed) || echo "Error"
 done
 
 # Give any argument for logging upload speed also.
-
-if [ $# ]; then
+if [ $# -ne 0 ]; then
     echo $(date) > $HOME/upspeed
+echo '' >> $HOME/upspeed
     for((i=0;i<10;i++));do
-        command -v speedtest && speedtest --no-download |grep ^Upload |tee $HOME/upspeed
+        command -v speedtest >/dev/null && speedtest --no-download |grep ^Upload |tee -a $HOME/upspeed
     done
 fi
