Minor changes.
Signed-off-by: Chinmay Chhajed <chinmay.chhajed@espressif.com>

diff --git a/netspeed b/netspeed
--- a/netspeed
+++ b/netspeed
@@ -2,7 +2,7 @@
 
 echo $(date) > $HOME/downspeed
 for((i=0;i<10;i++));do
-    (command -v speedtest >/dev/null && speedtest --no-upload |grep ^Download >>$HOME/downspeed) || echo "Error"
+    (command -v speedtest >/dev/null && speedtest --no-upload |grep ^Download |tee $HOME/downspeed) || echo "Error"
 done
 
 # Give any argument for logging upload speed also.
@@ -10,6 +10,6 @@ done
 if [ $1 ]; then
     echo $(date) > $HOME/upspeed
     for((i=0;i<10;i++));do
-        command -v speedtest && speedtest --no-download |grep ^Upload >>$HOME/upspeed
+        command -v speedtest && speedtest --no-download |grep ^Upload |tee $HOME/upspeed
     done
 fi
